# 端口，部署到服务器时推荐8080
server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/db_community?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: #用户名
    password: #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置邮件发送
  mail:
    host: smtp.qq.com
    username: # 邮箱
    password: # 邮箱密码
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

# redis配置
redis:
  database: 0
  host: 127.0.0.1 # redis地址
  port: 6379


sender:
  email: # 填写发送者邮箱

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lhx.community.mapper

# GitHub登录参数，根据申请到的填写
github:
  client_id:
  client_secret:
  redirect_uri: http://localhost:8080/githubCallback

# 日志配置
logging:
  file:
    name: log/community.log
    max-size: 200MB
    max-history: 30
  level:
    com.lhx.community.mapper: debug
    root: info

